shopt -s extglob
echo "AR   library.a"
source $LOST_BUILDMK_ROOT/config.sh

$LOST_TOOLS_AR rs library.a !(weak_stubs).o */*.o */*/*.o $LOST_BUILDMK_ROOT/src/lib/{*.o,*/*.o,*/*/*.o}

echo "LD   library.so"
$LOST_TOOLS_LD -shared -soname=libc -olibrary.so --whole-archive library.a weak_stubs.o --no-whole-archive $LIB_GCC
$LOST_TOOLS_STRIP -s library.so -o $1/system/libc.so
