shopt -s extglob
source $LOST_BUILDMK_ROOT/config.sh

echo "LD   $1/apps/pashello"
$LOST_TOOLS_LD -opashello $LDSCRIPT *.o --start-group ../lib/units/*.a $2 --end-group
$LOST_TOOLS_STRIP -s pashello -o $1/apps/pashello
