shopt -s extglob
source $LOST_BUILDMK_ROOT/config.sh

echo "LD   $1/modules/e1000"
$LOST_TOOLS_LD -oe1000.mod $LDSCRIPT *.o --start-group $2 --end-group
$LOST_TOOLS_STRIP -s e1000.mod -o $1/modules/e1000
