shopt -s extglob
source $LOST_BUILDMK_ROOT/config.sh

echo "LD   $1/modules/vterm"
$LOST_TOOLS_LD $LDSCRIPT -ovterm.mod  *.o keymaps/de.o --start-group $2 --end-group
$LOST_TOOLS_STRIP -s vterm.mod -o $1/modules/vterm
