shopt -s extglob
export LOST_BUILDMK_ROOT=$3
source $3/config.sh

KERNEL=../..

cp $KERNEL/smp/rm_trampoline.o .
$LOST_TOOLS_OBJCOPY -B i386:i386 -I binary -O elf32-i386 rm_trampoline.o rm_trampo_conv.o
rm rm_trampoline.o

echo "LD   $1/kernel/tyndur2"
$LOST_TOOLS_LD -otyndur2.krn -Tkernel.ld header.o --start-group !(header).o */*.o  $KERNEL/*.o $KERNEL/*/!(rm_trampoline).o $KERNEL/lostio/*/*.o $LOST_BUILDMK_ROOT/src/lib/library.a $2 --end-group
mv tyndur2.krn $1/kernel/tyndur2
