shopt -s extglob
source $LOST_BUILDMK_ROOT/config.sh

echo "LD   $1/modules/kbc"
$LOST_TOOLS_LD -m elf_i386 -okbc.mod $LDSCRIPT *.o --start-group $2 --end-group
$LOST_TOOLS_STRIP -s kbc.mod -o $1/modules/kbc
