shopt -s extglob
source $LOST_BUILDMK_ROOT/config.sh

echo "LD   $1/modules/tcpip"
$LOST_TOOLS_LD $LDSCRIPT -otcpip.mod  *.o --start-group $2 --end-group
$LOST_TOOLS_STRIP -s tcpip.mod -o $1/modules/tcpip
