shopt -s extglob
source $LOST_BUILDMK_ROOT/config.sh

echo "LD   $1/modules/sis900"
$LOST_TOOLS_LD -osis900.mod $LDSCRIPT *.o --start-group $2 --end-group
$LOST_TOOLS_STRIP -s sis900.mod -o $1/modules/sis900
