shopt -s extglob
source $LOST_BUILDMK_ROOT/config.sh

echo "LD   $1/modules/sysinfo"
$LOST_TOOLS_LD $LDSCRIPT -osysinfo.mod  *.o --start-group $2 --end-group
$LOST_TOOLS_STRIP -s sysinfo.mod -o $1/modules/sysinfo
