shopt -s extglob
source $LOST_BUILDMK_ROOT/config.sh

echo "LD   $1/modules/init"
$LOST_TOOLS_LD $LDSCRIPT -oinit.mod  *.o */*.o --start-group $2 --end-group
$LOST_TOOLS_STRIP -s init.mod -o $1/modules/init
