shopt -s extglob
source $LOST_BUILDMK_ROOT/config.sh

echo "LD   $1/apps/kirc"
$LOST_TOOLS_LD -okirc $LDSCRIPT *.o --start-group ../lib/units/*.a $2 --end-group
$LOST_TOOLS_STRIP -s kirc -o $1/apps/kirc
