shopt -s extglob
source $LOST_BUILDMK_ROOT/config.sh

echo "LD   $1/modules/file"
$LOST_TOOLS_LD -ofile.mod $LDSCRIPT *.o --start-group $2 --end-group
$LOST_TOOLS_STRIP -s file.mod -o $1/modules/file
