shopt -s extglob
source $LOST_BUILDMK_ROOT/config.sh

echo "LD   $1/apps/lpt"
$LOST_TOOLS_LD -olpt.mod $LDSCRIPT *.o lang/*.o --start-group ../lib/units/*.a $2 --end-group
$LOST_TOOLS_STRIP -s lpt.mod -o $1/apps/lpt
