shopt -s extglob
source $LOST_BUILDMK_ROOT/config.sh

echo "LD   $1/modules/rpcbench"
$LOST_TOOLS_LD $LDSCRIPT -orpcbench.mod  --start-group *.o $2 --end-group
$LOST_TOOLS_STRIP -s rpcbench.mod -o $1/modules/rpcbench
