shopt -s extglob
source $LOST_BUILDMK_ROOT/config.sh

echo "LD   $1/apps/sh"

if [ -z "`grep '#define CONFIG_SHELL_BUILTIN_ONLY' ../../../include/lost/config.h`" ];
then
	$LOST_TOOLS_LD -osh $LDSCRIPT *.o lang/*.o --start-group $2 --end-group
else
	$LOST_TOOLS_LD -osh $LDSCRIPT *.o lang/*.o cmds/*.o --start-group $2 --end-group
fi

$LOST_TOOLS_STRIP -s sh -o $1/apps/sh
