shopt -s extglob
source $LOST_BUILDMK_ROOT/config.sh

echo "LD   $1/modules/pcnet"
$LOST_TOOLS_LD $LDSCRIPT -opcnet.mod  *.o --start-group $2 --end-group
$LOST_TOOLS_STRIP -s pcnet.mod -o $1/modules/pcnet
