shopt -s extglob
source $LOST_BUILDMK_ROOT/config.sh

echo "LD   $1/modules/ne2k"
$LOST_TOOLS_LD $LDSCRIPT -one2k.mod  *.o --start-group $2 --end-group
$LOST_TOOLS_STRIP -s ne2k.mod -o $1/modules/ne2k
