shopt -s extglob
source $LOST_BUILDMK_ROOT/config.sh

echo "LD   $1/modules/ramdisk"
$LOST_TOOLS_LD -oramdisk.mod $LDSCRIPT *.o --start-group $2 --end-group
$LOST_TOOLS_STRIP -s ramdisk.mod -o $1/modules/ramdisk
