shopt -s extglob
source $LOST_BUILDMK_ROOT/config.sh

echo "LD   $1/modules/rtl8139"
$LOST_TOOLS_LD $LDSCRIPT -ortl8139.mod  *.o --start-group $2 --end-group
$LOST_TOOLS_STRIP -s rtl8139.mod -o $1/modules/rtl8139
