shopt -s extglob
source $LOST_BUILDMK_ROOT/config.sh

echo "LD   $1/modules/rtl8168b"
$LOST_TOOLS_LD $LDSCRIPT -ortl8168b.mod  *.o --start-group $2 --end-group
$LOST_TOOLS_STRIP -s rtl8168b.mod -o $1/modules/rtl8168b
