shopt -s extglob
source $LOST_BUILDMK_ROOT/config.sh

echo "LD   $1/modules/floppy"
$LOST_TOOLS_LD -ofloppy.mod $LDSCRIPT *.o --start-group $2 --end-group
$LOST_TOOLS_STRIP -s floppy.mod -o $1/modules/floppy
