shopt -s extglob
source $LOST_BUILDMK_ROOT/config.sh

echo "LD   $1/apps/getterm"

$LOST_TOOLS_LD -ogetterm $LDSCRIPT --start-group *.o $2 --end-group

$LOST_TOOLS_STRIP -s getterm -o $1/apps/getterm
